### ISSUE TITLE
Overall main tasks

### ISSUE THREAD

**Issue by corymosiman12** [BuildingSync/BuildingSync-gem#58]
Based on the review of PR https://github.com/BuildingSync/BuildingSync-gem/pull/56, define needs for next BSync gem development push

**Comment by TMaile** [comment]
Main tasks
- [x] _address review comments in PR #56 (Issue: #69) [DA_PullReq56 ] - MERGED PR #71_
- [x] _update BldgSync to OpenStudio 3.0 in PR #68 (Issue: #63) [DA_Update] MERGED_ 
- [x] refactor code that calls parametric schedules (#67) - Reviewed - NEEDS DISCUSSION
- [x] _refactor temp helper functions (Issue: #66, PR #70) [DA_Update_refTmp] MERGED_
- [ ] OPTIONAL: Update selection tool (Issue: #64)
- [x] cleanup of branches
- [x] Documentation 100% done
- [ ] Packaged released to rubygems.org

other pull requests:
- [X] _#73 Refactor code from spec to new generator class - MERGED_
- [x] #77 Refactoring the gather_results function - DONE - addressing review comments - FIXED remaining BUGS
- [X] _#76 Replacing some of the UDF - MERGED_
- [X] #83 finished function to determine baseline and measured scenarios - review comments addressed

open issues
- [X] #74 [DA_Update_EEM] Conflicting file names found - removed duplicates from OpenStudio-EE-Gem buildingsync_measures branch for now
- [x] #78 Adjust the way we determine baseline and simulated scenarios - DONE - PR #83
- [x] #62 decide if we should move NUM_BUILDINGS_PARALLEL to runner
- [x] #48 Maximum underground floors (1) - problem with new L100_Audit.xml test file. [DA_PullReq56]

**Comment by TMaile** [comment]
- [DA_PullReq56] 
     - added proper error message if a BldgSync.xml file has more than 1 underground story
- [buildingsync_measures]
   - removed duplicate measures for now
- [DA_PullReq56_RefGR] 
   - Reviewed Mrigesh's code and requested some changes
- [DA_Update_UDF]
   - resolved issues in UDF branch and sent some to Mrigesh #76
- Merged Pull Request #71
- Merged Pull Request #73

**Comment by TMaile** [comment]
- adding functions to check if measures are available across all measure gems
- debugging test failures in various branches
- #76 Replacing some of the UDF almost completed
- refactor parametric schedule code

**Comment by TMaile** [comment]
- finished implementation of UDF task and merged pull request #76 
- finished function to determine baseline and measured scenarios #83 - done and review comments addressed
- refactored parametric schedule code - created pull request #80 - looking into review comments
- refactored gather results function #77 - looking into review comments

**Comment by TMaile** [comment]
- merged pull request https://github.com/BuildingSync/BuildingSync-gem/pull/83 to early
   -  resolved remaining bugs in new branch: DA_PullReq56_Old-triage
- merged pull request https://github.com/BuildingSync/BuildingSync-gem/pull/77
- finished test code for parametric schedule generation. NEED to discuss

**Comment by TMaile** [comment]
- merged all branches into DA_Update to get a complete code base (except DA_Update_RefSched pending Corys approval)
- need to discuss the "bldgsync_measures" branch in the ee-gem again, everything else is in sync with "develop" branches
-

**Comment by corymosiman12** [comment]
Marking this as complete.  Just need to release.
