### ISSUE TITLE
[DA] Address review comments of large pull request #56

### ISSUE THREAD

**Issue by TMaile** [BuildingSync/BuildingSync-gem#69]
- [x] address review comments
- [x] remove code that references parametric schedules (depends on review and potential active use of DA branch)
- [x] initiate another round of review and if ok then finally merge PR #56 (without the schedule code)

**Comment by corymosiman12** [comment]
@TMaile please finish addressing the following comments.  These were things I still saw as outstanding (might have missed some updates you have already made though).  As you go through and address, can you just add minor branches and add new PRs into `DA_Update` to make it easier to track these getting addressed - thanks.
 
- [x] https://github.com/BuildingSync/BuildingSync-gem/pull/56#discussion_r416060583
- [x] https://github.com/BuildingSync/BuildingSync-gem/pull/56#discussion_r416062788
- [x] https://github.com/BuildingSync/BuildingSync-gem/pull/56#discussion_r416060583
- [x] https://github.com/BuildingSync/BuildingSync-gem/pull/56#discussion_r416058509
- [x] https://github.com/BuildingSync/BuildingSync-gem/pull/56#discussion_r478479922
- [x] https://github.com/BuildingSync/BuildingSync-gem/pull/56#discussion_r416064645
- [x] https://github.com/BuildingSync/BuildingSync-gem/pull/56#discussion_r416064759
- [x] https://github.com/BuildingSync/BuildingSync-gem/pull/56#discussion_r416071255 refactor gather_results [DA_PullReq56_RefGR] #77 
- [x] https://github.com/BuildingSync/BuildingSync-gem/pull/56#discussion_r416072765 add year as a parameter [DA_PullReq56_RefGR] #77
- [x] https://github.com/BuildingSync/BuildingSync-gem/pull/56#discussion_r416073125 add year as a parameter [DA_PullReq56_RefGR] #77
- [x] https://github.com/BuildingSync/BuildingSync-gem/pull/56#discussion_r478497514 [DA_Update_UDF] update occupancy_classification_original
- [x] https://github.com/BuildingSync/BuildingSync-gem/pull/56#discussion_r416108870 [DA_Update_UDF] remove user defined fields
- [x] https://github.com/BuildingSync/BuildingSync-gem/pull/56#discussion_r416120329
- [x] https://github.com/BuildingSync/BuildingSync-gem/pull/56#discussion_r416189369
- [x] https://github.com/BuildingSync/BuildingSync-gem/pull/56#discussion_r416222425

We also need to better align the standard definition of a 'Baseline Modeled' model and a 'Measured' scenario.  See these [Scenario Types](https://github.com/BuildingSync/TestSuite/blob/feat/python-tools-reorg/docs/Reports%20and%20Scenarios.md#scenario-types).  If this gets wrapped up in a new issue (#78) or something, that works too.  This would address comments:
- [x] https://github.com/BuildingSync/BuildingSync-gem/pull/56#discussion_r416055033
- [x] https://github.com/BuildingSync/BuildingSync-gem/pull/56#discussion_r416056103

Can you confirm that updating of test files to schema 2.1.0 will happen (a bunch of these comments)?
- [x] https://github.com/BuildingSync/BuildingSync-gem/pull/56#discussion_r416219934 where to get the latest L000_Instance1.xml file from

Also, what do you think about this suggestion (maybe open up new issue and label as `enhancement`):
- [x] https://github.com/BuildingSync/BuildingSync-gem/pull/56#discussion_r416223424  created new issue #72

**Comment by TMaile** [comment]
this is finally done with a couple of follow on issues:
- #72 
- #78

and related pull requests:
- #77
- #76
